services:
  - type: web
    name: snapyz-backend
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: chmod +x ./start.sh && ./start.sh
    envVars:
      - key: DATABASE_URL
        value: postgresql://ab:ijyx5AuWujmQFO8ylDOp55RwBFxIV9pH@dpg-d0ehqre5dus73fjdk2g-a.oregon-postgres.render.com/snapyz
      - key: PORT
        value: 10000
    autoDeploy: true
    healthCheckPath: /
