services:
  - type: web
    name: snapyz-backend
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: DATABASE_URL
        value: postgresql://ab:ijyx5AuWujmQFO8ylDOp55RwBFxIV9pH@dpg-d0ehqgre5dus73fjdk2g-a.oregon-postgres.render.com/snapyz
      - key: PORT
        value: 10000
    autoDeploy: true
    healthCheckPath: /
